#-----------------------------------------------------------------------
# Raspberry Pi 3
#
# tkyonezu/ubuntu - Ubuntu ARMv7 version
#
# build : docker build -t tkyonezu/ubuntu .
#
# Copyright (c) 2017 Takeshi Yonezu
# All Rights Reserved.
#-----------------------------------------------------------------------
FROM armv7/armhf-ubuntu

RUN apt update  && \
    apt -y upgrade

CMD ["/bin/bash"]
